baseURL = 'https://joerg-lohrer.de/'
languageCode = 'de'
defaultContentLanguage = 'de'
title = 'Jörg Lohrer'
theme = 'tailwind'
# SEO keywords and description for your site.
keywords = "OER, Religionspädagogik, Bildung, Religion, Hugo"
subtitle = "Jörg Lohrer - Webseite"



[permalinks]
  posts = "/:year/:month/:day/:slug.html"

[outputs]
home = ["HTML", "RSS"]


[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'Impressum'
    pageRef = '/Impressum'
    weight = 30
[[menus.main]]
    name = 'Schlagworte'
    pageRef = '/tags'
    weight = 20
[[menus.main]]
    name = 'Mastodon'
    pre = '<i class="fa fa-heart"></i>'
    url = 'https://reliverse.social/@joerglohrer'
    weight = 40
[menus.main.params]
      rel = 'external'

[params.header]
logo = "joerg-profil-2024.webp"


[params]
  [[params.jsonLD]]
  enabled = true

  [params.social_media]

    [[params.social_media.items]]
    enabled = true
    title = 'Mastodon'
    icon = 'brand-mastodon'
    link = 'https://reliverse.social/@joerglohrer'

    [[params.social_media.items]]
    enabled = true
    title = 'nostr'
    icon = 'brand-nostr'
    link = 'https://nostter.app/npub1f7jar3qnu269uyx5p0e4v24hqxjnxysxudvujza2ur5ehltvdeqsly2fx9'

    [[params.social_media.items]]
    enabled = true
    title = 'Bluesky'
    icon = 'brand-bluesky'
    link = 'https://bsky.app/profile/joerglohrer.bsky.social'

    [[params.social_media.items]]
    enabled = true
    title = 'Instagram'
    icon = 'brand-instagram'
    link = 'https://www.instagram.com/joerglohrer'

[taxonomies]
category = "Kategorien"
tag = "Schlagworte"
series = "Serien"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false


[pwa]
  enabled = false
  icon = "logo.png" # should be in assets
  icon_sizes = [192, 512]

  # will be used as the manifest.json file and merge the default one
  # https://developer.mozilla.org/en-US/docs/Web/Manifest
  # https://web.dev/add-manifest/
  [pwa.manifest]
  description = "Webseite Jörg Lohrer"